DROP TABLE IF EXISTS skills CASCADE;

CREATE TABLE opportunities (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id),
  name VARCHAR(255) NOT NULL,
  date NOT NULL,
  note VARCHAR(255) NOT NULL
);